name: Build Packages for AlmaLinux (RHEL), CentOS, Debian, and Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-ubuntu-24_04:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential pkg-config libgtkmm-3.0-dev dpkg-dev
      - name: Build binary
        run: make build
      - name: Build deb package
        run: make deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-ubuntu-24.04-bin
          path: bin/sgt
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-ubuntu-24.04-deb
          path: simple-gtk-tools_1.0_amd64.deb

  build-ubuntu-22_04:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential pkg-config libgtkmm-3.0-dev dpkg-dev
      - name: Build binary
        run: make build
      - name: Build deb package
        run: make deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-ubuntu-22.04-bin
          path: bin/sgt
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-ubuntu-22.04-deb
          path: simple-gtk-tools_1.0_amd64.deb

  build-alma-9:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build in AlmaLinux 9 container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace almalinux:9 \
          bash -c "dnf install -y epel-release && dnf config-manager --set-enabled crb && dnf install -y make gcc-c++ pkgconf-pkg-config gtkmm3-devel rubygems && gem install fpm && make build && make rpm"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-alma-9-bin
          path: bin/sgt
      - name: Upload rpm package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-alma-9-rpm
          path: "*.rpm"

  build-alma-8:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build in AlmaLinux 8 container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace almalinux:8 \
          bash -c "dnf install -y epel-release && dnf config-manager --set-enabled crb && dnf install -y make gcc-c++ pkgconf-pkg-config gtkmm3-devel rubygems && gem install fpm && make build && make rpm"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-alma-8-bin
          path: bin/sgt
      - name: Upload rpm package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-alma-8-rpm
          path: "*.rpm"

  build-centos-7:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build in CentOS 7 container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace centos:7 \
          bash -c "yum install -y epel-release && yum install -y make gcc-c++ pkgconfig gtkmm3-devel rubygems && gem install fpm && make build && make rpm"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-centos-7-bin
          path: bin/sgt
      - name: Upload rpm package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-centos-7-rpm
          path: "*.rpm"

  build-debian-bookworm:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential pkg-config libgtkmm-3.0-dev dpkg-dev
      - name: Build binary
        run: make build
      - name: Build deb package
        run: make deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-debian-bookworm-bin
          path: bin/sgt
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-debian-bookworm-deb
          path: simple-gtk-tools_1.0_amd64.deb

  build-debian-bullseye:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential pkg-config libgtkmm-3.0-dev dpkg-dev
      - name: Build binary
        run: make build
      - name: Build deb package
        run: make deb
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sgt-debian-bullseye-bin
          path: bin/sgt
      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: sgt-debian-bullseye-deb
          path: simple-gtk-tools_1.0_amd64.deb


  upload-release-assets:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - build-ubuntu-24_04
      - build-ubuntu-22_04
      - build-alma-9
      - build-alma-8
      - build-centos-7
      - build-debian-bookworm
      - build-debian-bullseye
    steps:
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: find artifacts

      - name: Upload Ubuntu 24.04 deb to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-ubuntu-24.04-deb/simple-gtk-tools_1.0_amd64.deb
          asset_name: simple-gtk-tools_ubuntu-24.04_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Ubuntu 22.04 deb to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-ubuntu-22.04-deb/simple-gtk-tools_1.0_amd64.deb
          asset_name: simple-gtk-tools_ubuntu-22.04_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload AlmaLinux 9 rpm to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-alma-9-rpm/*.rpm
          asset_name: simple-gtk-tools_almalinux-9_1.0_x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload AlmaLinux 8 rpm to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-alma-8-rpm/*.rpm
          asset_name: simple-gtk-tools_almalinux-8_1.0_x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload CentOS 7 rpm to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-centos-7-rpm/*.rpm
          asset_name: simple-gtk-tools_centos-7_1.0_x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload Debian Bookworm deb to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-debian-bookworm-deb/simple-gtk-tools_1.0_amd64.deb
          asset_name: simple-gtk-tools_debian-bookworm_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Debian Bullseye deb to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/sgt-debian-bullseye-deb/simple-gtk-tools_1.0_amd64.deb
          asset_name: simple-gtk-tools_debian-bullseye_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
